# Generated by Django 5.1.6 on 2025-03-03 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('No_of_days', models.IntegerField(max_length=2)),
                ('emp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.employee')),
            ],
        ),
    ]
