# Generated by Django 5.1.6 on 2025-03-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_leaves'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='approved',
            field=models.BooleanField(null=True),
        ),
    ]
